Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Write-Step {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Message
    )

    Write-Host ''
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Assert-PathExists {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,
        [Parameter(Mandatory = $true)]
        [string]$Description
    )

    if (-not (Test-Path -LiteralPath $Path)) {
        throw "$Description not found: $Path"
    }
}

function Invoke-External {
    param(
        [Parameter(Mandatory = $true)]
        [string]$FilePath,
        [Parameter(Mandatory = $true)]
        [string[]]$Arguments
    )

    Write-Host ($FilePath + ' ' + ($Arguments -join ' '))
    & $FilePath @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Command failed with exit code $LASTEXITCODE."
    }
}

function Invoke-CmdChain {
    param(
        [Parameter(Mandatory = $true)]
        [string]$CommandLine
    )

    Write-Host ('cmd.exe /c ' + $CommandLine)
    & cmd.exe /c $CommandLine
    if ($LASTEXITCODE -ne 0) {
        throw "Command failed with exit code $LASTEXITCODE."
    }
}

function Remove-DirectoryIfPresent {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    if (-not (Test-Path -LiteralPath $Path)) {
        return
    }

    Remove-Item -LiteralPath $Path -Recurse -Force
}

function Remove-StaleArduinoBuildDirectories {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ScriptRoot,
        [Parameter(Mandatory = $true)]
        [string[]]$PreservePaths
    )

    $normalizedPreservePaths = @($PreservePaths | ForEach-Object {
        [System.IO.Path]::GetFullPath($_).TrimEnd('\')
    })

    Get-ChildItem -LiteralPath $ScriptRoot -Directory | Where-Object { $_.Name -like 'arduino_build*' } | ForEach-Object {
        $candidatePath = [System.IO.Path]::GetFullPath($_.FullName).TrimEnd('\')
        if ($normalizedPreservePaths -contains $candidatePath) {
            return
        }

        if (-not $candidatePath.StartsWith([System.IO.Path]::GetFullPath($ScriptRoot).TrimEnd('\'), [System.StringComparison]::OrdinalIgnoreCase)) {
            throw "Refusing to remove Arduino build directory outside the helper root: $candidatePath"
        }

        Remove-Item -LiteralPath $candidatePath -Recurse -Force
    }
}

function Ensure-ArduinoEigenLibrary {
    param(
        [Parameter(Mandatory = $true)]
        [string]$LibraryRoot,
        [Parameter(Mandatory = $true)]
        [string]$EigenSourceRoot
    )

    $eigenLibraryRoot = Join-Path $LibraryRoot 'Eigen'
    $srcRoot = Join-Path $eigenLibraryRoot 'src'
    $eigenIncludeRoot = Join-Path $srcRoot 'Eigen'
    $entryHeaderPath = Join-Path $srcRoot 'Eigen.h'
    $libraryPropertiesPath = Join-Path $eigenLibraryRoot 'library.properties'

    New-Item -ItemType Directory -Path $srcRoot -Force | Out-Null

    if (-not (Test-Path -LiteralPath $eigenIncludeRoot)) {
        New-Item -ItemType Junction -Path $eigenIncludeRoot -Target (Join-Path $EigenSourceRoot 'Eigen') | Out-Null
    }

    $unsupportedIncludeRoot = Join-Path $srcRoot 'unsupported'
    if (Test-Path -LiteralPath $unsupportedIncludeRoot) {
        Remove-Item -LiteralPath $unsupportedIncludeRoot -Force -Recurse
    }

    @(
        '#pragma once'
        ''
        '// Marker header for Arduino library discovery. Runtime code includes'
        '// Eigen through MazeMap/EigenCompat.h so this header stays zero-cost.'
    ) | Set-Content -Path $entryHeaderPath -Encoding ASCII

    @(
        'name=Eigen'
        'version=5.0.0'
        'author=Eigen Project'
        'maintainer=Eigen Project'
        'sentence=Repo-local staging wrapper for the shared Eigen checkout.'
        'paragraph=Generated by codex_verify/verify_latest_build.ps1 so Arduino can resolve Eigen headers without modifying the installed Teensy core.'
        'category=Data Processing'
        'includes=Eigen.h'
        'architectures=*'
    ) | Set-Content -Path $libraryPropertiesPath -Encoding ASCII

    return $LibraryRoot
}

function Assert-ArtifactFresh {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,
        [Parameter(Mandatory = $true)]
        [string]$Description,
        [Parameter(Mandatory = $true)]
        [datetime]$NotOlderThan
    )

    Assert-PathExists -Path $Path -Description $Description

    $item = Get-Item -LiteralPath $Path
    if ($item.LastWriteTime -lt $NotOlderThan) {
        throw ("{0} was not rebuilt by this run. LastWriteTime={1}; expected at or after {2}." -f $Description, $item.LastWriteTime, $NotOlderThan)
    }

    return $item
}

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $scriptRoot

$arduinoCli = 'C:\Program Files\Arduino IDE\resources\app\lib\backend\resources\arduino-cli.exe'
$vsDevCmd = 'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat'
$vstest = 'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe'

$sketchDir = Join-Path $repoRoot 'MazeMap\MazeMap'
$eigenIncludeDir = Join-Path $repoRoot 'MazeMap\eigen-5.0.0'
$arduinoLibrariesDir = Join-Path $scriptRoot 'arduino_libraries'
$arduinoEigenLibraryDir = Join-Path $arduinoLibrariesDir 'Eigen'
$solutionPath = Join-Path $repoRoot 'MazeMap\MazeMap.sln'
$runStamp = Get-Date -Format 'yyyyMMdd_HHmmss_fff'
$canonicalBuildPath = Join-Path $scriptRoot 'arduino_build'
$buildPath = Join-Path $scriptRoot ('arduino_build_work_' + $runStamp)
$firmwareOutputDir = Join-Path $canonicalBuildPath 'firmware'
$hexPath = Join-Path $firmwareOutputDir 'MazeMap.ino.hex'
$testDllPath = Join-Path $repoRoot 'MazeMap\x64\Release\MazeMapTest.dll'
$fqbn = 'teensy:avr:teensy41'
$runStartedAt = Get-Date

Assert-PathExists -Path $arduinoCli -Description 'Arduino CLI'
Assert-PathExists -Path $vsDevCmd -Description 'Visual Studio developer command script'
Assert-PathExists -Path $vstest -Description 'VSTest console'
Assert-PathExists -Path $sketchDir -Description 'Arduino sketch directory'
Assert-PathExists -Path $eigenIncludeDir -Description 'Shared Eigen include directory'
Assert-PathExists -Path $solutionPath -Description 'MazeMap solution'

$eigenIncludeDir = (Resolve-Path -LiteralPath $eigenIncludeDir).Path
$arduinoLibrariesDir = Ensure-ArduinoEigenLibrary -LibraryRoot $arduinoLibrariesDir -EigenSourceRoot $eigenIncludeDir
$arduinoEigenLibraryDir = (Resolve-Path -LiteralPath $arduinoEigenLibraryDir).Path

Push-Location $repoRoot
try {
    Remove-StaleArduinoBuildDirectories -ScriptRoot $scriptRoot -PreservePaths @($canonicalBuildPath)
    Remove-DirectoryIfPresent -Path $canonicalBuildPath
    Remove-DirectoryIfPresent -Path $buildPath

    New-Item -ItemType Directory -Path $firmwareOutputDir -Force | Out-Null

    Write-Step 'Compiling the Teensy sketch'
    Invoke-External -FilePath $arduinoCli -Arguments @(
        'compile',
        '--clean',
        '--fqbn', $fqbn,
        '--libraries', $arduinoLibrariesDir,
        '--library', $arduinoEigenLibraryDir,
        '--build-path', $buildPath,
        '--output-dir', $firmwareOutputDir,
        $sketchDir
    )

    $firmwareImage = Assert-ArtifactFresh -Path $hexPath -Description 'Compiled firmware image' -NotOlderThan $runStartedAt
    Write-Host ("Built {0} ({1}, {2} bytes)" -f $firmwareImage.FullName, $firmwareImage.LastWriteTime, $firmwareImage.Length) -ForegroundColor Green

    Write-Step 'Rebuilding the Release solution'
    Invoke-CmdChain -CommandLine ('call "{0}" -no_logo && msbuild "{1}" /t:Rebuild /p:Configuration=Release /p:Platform=x64 /v:m' -f $vsDevCmd, $solutionPath)

    $testDll = Assert-ArtifactFresh -Path $testDllPath -Description 'Release test binary' -NotOlderThan $runStartedAt
    Write-Host ("Built {0} ({1}, {2} bytes)" -f $testDll.FullName, $testDll.LastWriteTime, $testDll.Length) -ForegroundColor Green

    Write-Step 'Running the Release unit tests'
    Invoke-External -FilePath $vstest -Arguments @($testDll.FullName)

    Remove-StaleArduinoBuildDirectories -ScriptRoot $scriptRoot -PreservePaths @($canonicalBuildPath)
    Remove-DirectoryIfPresent -Path $buildPath

    Write-Step 'Build and test completed'
    Write-Host ("Latest firmware image: {0}" -f $firmwareImage.FullName) -ForegroundColor Green
    Write-Host ("Release test binary: {0}" -f $testDll.FullName) -ForegroundColor Green
}
finally {
    Pop-Location
}
